### ISSUE TITLE
Trade feed or Order Book feeds dies after a while -> need self-healing thread restart  

### ISSUE THREAD

**Issue by igor3210** [BitcoinExchangeFH/BitcoinExchangeFH#102]
Hi,

I am running the software since a while to download price data in CVS. I observed 2 issues:
1) once the GDAX feed updated only trades but no book (bid, asks, etc), it keeps running forever with no warning/error
2) another time the trade feed of KRAKEN died, however, the book feed was still running and updating the file. again not errors/warnings

In both cases a simple restart solves the problem
`bitcoinexchangefh -csv -csvpath  path -instmts subscription.ini`

Is there a way to restart automatically the thread which takes care of reading the trades and/or the orderbook in case that this crashes? Possible reasons for crashing include lack of network connectivity for a limited time (my ISP is not that reliable).

Thanks

**Comment by JMedon** [comment]
Hi, I have the same issue with GDAX? someone can help make autorestart?
thanks in advance

**Comment by gavincyi** [comment]
1. What instrument did you run on? The issue happened once it started, or it had been running for a while?

2. My understanding is when the trade feed dies, it will reconnect again. Did such happen?

**Comment by JMedon** [comment]
Ad1. I run btcusd ltcusd and ethusd, and after two days btcusd and ltcusd has stopped receive orderbook data but has received trade data. ethusd receive both order and trade data.
2.No

**Comment by igor3210** [comment]
Hello @gavincyi ,

I was running BTCUSD, and based on my observations I can confirm that:
1) if trade feed dies (observed with KRAKEN), it will **not** reconnect again (or if it reconnects then the program is not able to deal with this, as it keeps the last state of the trade feed with no further updates)
2) if orderbook feed dies (observed with GDAX), it will **not** reconnect again (or if it reconnects then the program is not able to deal with this, as it keeps the last state of the orderbook feed with no further updates)

**Comment by igor3210** [comment]
To further comment:  the issue did not happen at start time, but after running for a while, it was fixed by restarting everything. I would not know how to reproduce the issue, but my intuition tells me that if you run a feed (let's say in GDAX) long enough this will happen with a quite high likelihood.

**Comment by JMedon** [comment]
Hi
One and only solution is to restart application after you do not receive new messages. So I made another python code to run, check status and restart connection after several seconds. Regards

**Comment by tanaytrivedi** [comment]
@JMedon can you give us some hint as to how you did this? Is it something like using subprocess or os to do the original call, then reading in the csv periodically and checking if the tail index is less than <30 seconds from right now. If it isnt, kill the currently running one and restart it? Is there any smarter way of detecting if the feed is dead? Do you get some indication from the output of the original call?

**Comment by gavincyi** [comment]
Closed due to a long period of inactivity. Issue should be resolved in 2019.1.1
