### ISSUE TITLE
[WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

### ISSUE THREAD

**Issue by JMedon** [BitcoinExchangeFH/BitcoinExchangeFH#104]
Hi
I can't connect to BitmexExchange because i receive error on the below:

[ExchGwBitmexWs]
Socket <ExchGwBitMEX> error:
 [WinError 10042] An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call

can you help?

**Comment by gavincyi** [comment]
Resolved in 2019.1.1
