### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by dreamyphone** [BitcoinExchangeFH/BitcoinExchangeFH#126]
got lots of following errors.

[MysqlClient]
SQL error: (0, '')
SQL: insert into exch_bitfinex_btcusd_snapshot_20180329 (id,trade_px,trade_volume,b1,b2,b3,b4,b5,a1,a2,a3,a4,a5,bq1,bq2,bq3,bq4,bq5,aq1,aq2,aq3,aq4,aq5,order_date_time,trades_date_time,update_type) values (9,0.00000000,0.00000000,7506.60000000,7506.50000000,7505.60000000,7505.40000000,7503.60000000,7506.70000000,7508.90000000,7510,7511.70000000,7513.70000000,1.50056550,3.83631000,0.10000000,1.73800000,0.16347432,1.10400000,0.24558256,5,0.30000000,0.06660850,'20180329 07:42:37.747269','20000101 00:00:00.000000',1)

threads are racing to control the DB?

**Comment by ValmonZ** [comment]
Yes I have the same problem. After one day work inserting into mysql falls

**Comment by ValmonZ** [comment]
does anybody know how adjust mysql server?

**Comment by ClaudiuAGGA** [comment]
Have the same problem, did you guys solved it?

**Comment by cbearden11** [comment]
I also have the same problem. Did anyone ever solve this? I read some other issues related to pymysql that talk about using connection pooling, but i'm not sure how to implement pooling with BitcoinExchangeFH.

**Comment by gavincyi** [comment]
Autoincrement id management falls back to database server in 2019.1.1
