### ISSUE TITLE
429: too many requests on Gdax.

### ISSUE THREAD

**Issue by atisharma** [BitcoinExchangeFH/BitcoinExchangeFH#128]
The Gdax order book seems to work via the REST API. In the code, you have 
```    def get_order_book_worker(self, instmt):
          ......
           time.sleep(1)
```

There is a limit of 3 requests per second.

Since the sleep(1) is hardcoded, this results in a 'too many requests' error when subscribing to more than three Gdax instruments.

This could be handled by allowing that time constant to be larger or with a backoff.

**Comment by ruXlab** [comment]
I've encounter the same problem. I'm wondering why does it happen if GDAX supposed to work via WebSockets

**Comment by gavincyi** [comment]
Good point that GDAX should be queried from websockets. Will work on that.

**Comment by gavincyi** [comment]
Enhanced in 2019.1.1
