### ISSUE TITLE
how to increase depth from 5 to 10

### ISSUE THREAD

**Issue by cbearden11** [BitcoinExchangeFH/BitcoinExchangeFH#133]
Are there any suggestions on how I can increase the order book depth from 5 to 10?
If I use mysql, I see where I can duplicate the existing fields in the tables from b1-b10, and a1 to 10.
as an example...

**Comment by gavincyi** [comment]
Not supported at this moment but will be enhanced.

**Comment by gavincyi** [comment]
Resolved in 2019.1.1
