### ISSUE TITLE
Is there anyone still working on this project?

### ISSUE THREAD

**Issue by laci06** [BitcoinExchangeFH/BitcoinExchangeFH#135]
I would like to hire someone who can do some customization on this package, like adding new exchanges, making sure that all the included exchanges work etc. I am willing to pay.

Thank you!

**Comment by tcccapinfo** [comment]
I can help, reach out to me at info@tribecachelseacapital.com.

**Comment by laci06** [comment]
I have not seen your name among the contributors. Did you work on any similar project or why are you interested?

**Comment by gavincyi** [comment]
Currently I'm busy in full time job and my personal life so I don't actively maintain it / extend the exchanges. Meanwhile I'm rewriting and redesigning for the v2 which can cater more functionalities. You can either pay for someone to extend the current project, or wait for v2.

**Comment by gavincyi** [comment]
Version 2019.1.1 has been released. Welcome to experience a big improvement from it. :)
