### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by laci06** [BitcoinExchangeFH/BitcoinExchangeFH#140]
Hello Gavin,

I was trying to install the new version (thank you for the update).
However, I ran into the following problem:
Collecting zmq>=17.1.2 (from bitcoinexchangefh)
  Could not find a version that satisfies the requirement zmq>=17.1.2 (from bitcoinexchangefh) (from versions: 0.0.0)
No matching distribution found for zmq>=17.1.2 (from bitcoinexchangefh)

I am trying to install the package on ubuntu 18.04 and the python version is 3.6.7

What could it be?

**Comment by atisharma** [comment]
Can confirm, with anaconda 3 on 64 bit linux.
Version of zmq in pip lists "zmq (0.0.0)                    - You are probably looking for pyzmq."

**Comment by gavincyi** [comment]
Thanks for spotting it out. Resolved in 2019.1.2
