### ISSUE TITLE
Bids are sliced incorrectly

### ISSUE THREAD

**Issue by jdschaa** [BitcoinExchangeFH/BitcoinExchangeFH#144]
* Bitcoin exchange feedhandler version: 2019.1.3
* Python version: 3.6
* Operating System: fedora 27

### Description
When OrderBook._depth is less than the length of bids in an update, the worst bids are copied into OrderBook._bids instead of the best.

### What I Did
Ran with Binance BTC/USDT with default depth = 5. It retrieved 20 bids and copied the 5 lowest into self._bids.

To fix, add an offset = len(bids) - len(self._bids) to the bid indices when copying bid values.

**Comment by gavincyi** [comment]
Thanks for spotting out. The issue has been resolved in 2019.1.4.
