### ISSUE TITLE
python3 installed and this instruction line STILL does not work  bitcoinexchangefh --configuration example/configuration.yaml

### ISSUE THREAD

**Issue by johnda98** [BitcoinExchangeFH/BitcoinExchangeFH#162]
* Bitcoin exchange feedhandler version:
* Python version: 3  and there is no instructions for pip 9
* Operating System: ubuntu 1604

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
 see attached
![Screenshot from 2020-05-04 12-00-45](https://user-images.githubusercontent.com/13384285/80992510-3bf04380-8dff-11ea-95c2-e823310cce4a.png)

**Comment by johnda98** [comment]
Compatibility
The application is compatible with version higher or equal to python 3.0.

which I have and it still no joy getting this running

**Comment by gavincyi** [comment]
Basically the exception has already told you that python 2.7 is used to run the application. At least you should run the installation via pip3 not pip in Ubuntu when you install the application in the system Python.

**Comment by johnda98** [comment]
arhhh pip3 .. ok will try

*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.
