### ISSUE TITLE
Difference between CryptoStore & BFH?

### ISSUE THREAD

**Issue by yohplala** [BitcoinExchangeFH/BitcoinExchangeFH#163]
### Description

Hello Gavin,
Thanks a lot for sharing this geat piece of work. I have come over it, and I can only congratulate you!
Sorry to issue a ticket for my question; I intended to send you an email, as you propose to do when having a question, but I could not find your email address.

If I understand correctly, BitcoinExchangeFH is built on top of CCXT and CryptoFeed to retrieve crypto data.
When having a look to CryptoFeed, I could see that the author has also implemented CryptoStore which appears to operate similarly to BitcoinExchangeFH.

I am sorry to ask, do you think you could share about their differences?
I don't know if CryptoStore was already existing at the time you started BitcoinExchangeFH. If yes, what have been the lack in CryptoStore so that you started BFH?

I thank you in advance for your reply.
Bests,

**Comment by gavincyi** [comment]
Sorry for the late reply. 

> If I understand correctly, BitcoinExchangeFH is built on top of CCXT and CryptoFeed to retrieve crypto data.

Correct.

> I am sorry to ask, do you think you could share about their differences?

My project was first started to contain the exchange handler in the code base. After a while, the exchange coverage could not catch up with other projects like CryptoFeed (on websocket clients) and CCXT (on REST API clients), so I rewrite the whole framework to rely on the two libraries. The major difference is the BitcoinExchangeFH uses multiprocessing to handle multiple exchanges and handlers, while the CryptoFeed and CryptoStore uses asycnio. I believe there is no difference when you run a single exchange handler + a single data handler in a single process, but BitcoinExchangeFH slightly performs better on multiple exchange handlers.

**Comment by yohplala** [comment]
Hi Gavin, thanks for the clarification. I appreciate your feedback. Have a good day, Bests,
