### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Tastry** [BitcoinExchangeFH/BitcoinExchangeFH#190]
0xc00dE8De8F932304d5e5Ba675ed9D79783E0fD87

This is an ERC-20 (Ethereum) address. Do not send USDT over any other network to this address or your funds may be lost.

**Comment by Stargazerr1** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
