### ISSUE TITLE
change market get data time interval

### ISSUE THREAD

**Issue by cbearden11** [BitcoinExchangeFH/BitcoinExchangeFH#68]
Hi. Thanks for this awesome project!
Is there any way to change the interval of when market data is pulled, say from Bittrex?
I was looking for something like getting json data say every 1 or 5 min.
Thanks!

**Comment by gavincyi** [comment]
Thanks for that :)

Currently it is not supported but will enhance it in the future. Will keep you posted on the changes.

**Comment by cbearden11** [comment]
What would happen if I inserted a sleep statement in bitcoinexchangefh.py, which appears to have something to do with running the subscriptions window, with pulling the market data down? I'm wondering if this would possibly slow it down some? Thanks for your insight!

**Comment by gavincyi** [comment]
The sleep occurs on each thread (or exchange).

For example, it [sleeps](https://github.com/Aurora-Team/BitcoinExchangeFH/blob/master/befh/exch_yunbi.py#L213) between each call of getting the depth and the trades.

**Comment by cbearden11** [comment]
Understood. Thank you for the quick update and info!

**Comment by QuantScientist** [comment]
Hi,
So what is the default time interval for pulling data from the exchanges? What do I have to change to pull data every second or minute? 
Many thanks.
